server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.json

jwt:
  secret: "${TOKEN-SECRET}"
  expiration: 3600000 # 1 hora (milisegundos)

management:
  endpoints:
    web:
      exposure:
        include: "health"



whatsapp:
  api:
    url: "https://graph.facebook.com/v22.0/%s/messages"
    token: "${TOKEN}"
    numberid: "${NUMBER-ID}"
  webhook:
    secret: "${WHATSAPP-WEBHOOK-SECRET}"
    verify:
      token: "${WHATSAPP-VERIFY-TOKEN}"
